"""Add collection table

Revision ID: 6b5e9fc83c15
Revises: a63a5fd79ce9
Create Date: 2026-01-19 11:08:49.741482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b5e9fc83c15'
down_revision: Union[str, Sequence[str], None] = 'a63a5fd79ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectioncard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collectioncard_card_id'), 'collectioncard', ['card_id'], unique=False)
    op.create_index(op.f('ix_collectioncard_user_id'), 'collectioncard', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collectioncard_user_id'), table_name='collectioncard')
    op.drop_index(op.f('ix_collectioncard_card_id'), table_name='collectioncard')
    op.drop_table('collectioncard')
    # ### end Alembic commands ###
