"""add_card_model_and_cache

Revision ID: a63a5fd79ce9
Revises: d5a4a4b6cea5
Create Date: 2026-01-18 23:55:57.704692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a63a5fd79ce9'
down_revision: Union[str, Sequence[str], None] = 'd5a4a4b6cea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mana_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('oracle_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('image_uris', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_deckcard_card', 'deckcard', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_deckcard_card', 'deckcard', type_='foreignkey')
    op.drop_table('card')
    # ### end Alembic commands ###
