"""add legalities to card

Revision ID: b73e9561f393
Revises: d8163c4049fb
Create Date: 2026-01-21 19:56:22.281208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73e9561f393'
down_revision: Union[str, Sequence[str], None] = 'd8163c4049fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('legalities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'legalities')
    # ### end Alembic commands ###
