"""Add produced_mana field

Revision ID: d8163c4049fb
Revises: 6b5e9fc83c15
Create Date: 2026-01-19 21:05:34.756094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8163c4049fb'
down_revision: Union[str, Sequence[str], None] = '6b5e9fc83c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('produced_mana', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'produced_mana')
    # ### end Alembic commands ###
